### ISSUE TITLE
Add restrictions for items usage

### ISSUE THREAD

**Issue by makeevrserg** [Astra-Interactive/AspeKt#129]
The restrictions should restrict usage of blocks and items
```yaml
restrictions:
  restriction_1:
    permission: "aspekt.restrictions.restriction_1"
    items:
      - "TRIDENT"
      - "DIAMOND_BLOCK"
```
