### ISSUE TITLE
Admin private system

### ISSUE THREAD

**Issue by makeevrserg** [Astra-Interactive/AspeKt#7]
Claiming: 
1. Claiming by chunk - /aspekt claim
2. Flag management - /aspekt chunk flag \<flag\> \<bool\>
```yaml
chunks:
  - x: 0
    z: 0
    author: RomaRoman
    flags:
      break: false
```
