### ISSUE TITLE
[WIP-FEATURE] Economy

### ISSUE THREAD

**Issue by makeevrserg** [Astra-Interactive/AspeKt#75]
### Overview

Economy feature will provide player currency economy. They will be able to exchange it, put into banks etc.

#### API

There should be Vault support. Inside Vault implementation, we should check for non-blocking call. The call of function
shouldn't be on Main thread.

#### Storage

All the information is stored on SQL database.

- `SQLite` is not supported because of lack of concurrency
- `H2` Is default
- `MySQL`

#### Configuration

```yml
# Configuration defined in eko-config.yml
database:
  # Use MySql
  type: MySql
  host: 0.0.0.0
  port: 25565
  user: user
  password: password
  name: DATABASE_NAME
  # Use H2
  type: H2

# Custom currencies are defined in `currencies.yml`.
DUBLON:
  id: "dublon"
  name: "Дублон"
  # Only one primary currency!
  is_primary: true
```

All custom currencies are inserted into database on reload or on start. If currency is present(the lookup is by string
id) then the currency should be updated. All configurations are taken from the database, not from `.yml` file.

At reload/initial configuration we also should check for primary currency. There should be only one primary currency.

#### SQL Tables

```mermaid
erDiagram
    CURRENCY {
        PK_string id
        string name
        bool is_primary
    }
    PLAYER_DATA {
        PK_string uuid
        REF_string currency_id
        string last_username
        double amount
    }

```

#### Commands

| Command                                       | Permission                        | Description                                   |
|:----------------------------------------------|:----------------------------------|:----------------------------------------------|
| `/ekon list`                                  | `aspekt.ekon.list`                | `List all currencies`                         |
| `/ekon top <currency> <page>`                 | `aspekt.ekon.top.<currency>`      | `List top player of <currency>`               |
| `/ekon balance <currency> [player]`           | `aspekt.ekon.balance.<currency>`  | `Balance of currency`                         |
| `/ekon transfer <currency> <player> <amount>` | `aspekt.ekon.transfer.<currency>` | `Transfer <amount> of <currency> to <player>` |
| `/ekon set <currency> <player> <amount>`      | `aspekt.ekon.set.<currency>`      | `Set <amount> of <currency> to <player>`      |
| `/ekon reload`                                | `aspekt.ekon.reload`              | `Reload economy module`                       |

#### Placeholder

| Placeholder                              | Description                                         |
|:-----------------------------------------|:----------------------------------------------------|
| `%ekon_balance_<currency>_<player>%`     | `Balance of player <currency>`                      |
| `%ekon_balance_<currency>_self%`         | `Self balance of <currency>`                        |
| `%ekon_balance_top_<currency>_<number>%` | `See top player of <currency> at position <number>` |

### Questions

- Should players be able to create banks? - Not in initial PR
- Should there be a feature to get credits? - Not in initial PR and only after banks
- How to create taxes? - Not in initial PR
- A way to define primary currency. - Define in .yml config
